#!/bin/bash 
##############################################################
# Check icingastats for collectd
#
# poil@quake.fr - 21/03/2011

HOSTNAME="${COLLECTD_HOSTNAME:-`hostname -s`}"
INTERVAL="${COLLECTD_INTERVAL:-60}"

while sleep "$INTERVAL"
do
  # latency
  AVGACTSVCLAT=$(icingastats --mrtg --data=AVGACTSVCLAT)
  AVGPSVSVCLAT=$(icingastats --mrtg --data=AVGPSVSVCLAT)
  AVGACTHSTLAT=$(icingastats --mrtg --data=AVGACTHSTLAT)
  AVGPSVHSTLAT=$(icingastats --mrtg --data=AVGPSVHSTLAT)

  # checks
  NUMSERVICES=$(icingastats --mrtg --data=NUMSERVICES)
  NUMACTSVCCHECKS5M=$(icingastats --mrtg --data=NUMACTSVCCHECKS5M)
  NUMPSVSVCCHECKS5M=$(icingastats --mrtg --data=NUMPSVSVCCHECKS5M)
  CHKPERCENT=$(( ( $NUMACTSVCCHECKS5M+$NUMPSVSVCCHECKS5M ) * 100 / $NUMSERVICES ))

  echo "PUTVAL $HOSTNAME/icinga/latency-active_check_services interval=$INTERVAL N:$AVGACTSVCLAT"
  echo "PUTVAL $HOSTNAME/icinga/latency-passive_check_services interval=$INTERVAL N:$AVGPSVSVCLAT"
  echo "PUTVAL $HOSTNAME/icinga/latency-active_check_hosts interval=$INTERVAL N:$AVGACTHSTLAT"
  echo "PUTVAL $HOSTNAME/icinga/latency-passive_check_hosts interval=$INTERVAL N:$AVGPSVHSTLAT"
  echo "PUTVAL $HOSTNAME/icinga/percent-5_min_checks interval=$INTERVAL N:$CHKPERCENT"
done

